### ISSUE TITLE
dxUpdatebaseTexture, DxbaseTexture do not exists

### ISSUE THREAD

**Issue by nikitafloy** [OvileAmriam/MTA-Cinecam_Handler#1]
Hello. What is dxUpdatebaseTexture and DxbaseTexture here?)

**Comment by ov-tron** [comment]
Ah this resource, is actually being refactored and will be more optimized in coming days, Will work as Assetify module soon. But for this existing version replace `DxbaseTexture` & `dxUpdatebaseTexture` with `dxCreateScreenSource` and `dxUpdateScreenSource` respectively..

**Comment by ov-tron** [comment]
> Hello. What is dxUpdatebaseTexture and DxbaseTexture here?)

^

**Comment by ov-anisa** [comment]
> Ah this resource, is actually being refactored and will be more optimized in coming days, Will work as Assetify module soon. But for this existing version replace `DxbaseTexture` & `dxUpdatebaseTexture` with `dxCreateScreenSource` and `dxUpdateScreenSource` respectively..

Ara ^_^

**Comment by nikitafloy** [comment]
> Ah this resource, is actually being refactored and will be more optimized in coming days, Will work as Assetify module soon. But for this existing version replace `DxbaseTexture` & `dxUpdatebaseTexture` with `dxCreateScreenSource` and `dxUpdateScreenSource` respectively..

Yeah, i did it. What about `reverseCinemPointationPoint` function?

**Comment by ov-tron** [comment]
> > Ah this resource, is actually being refactored and will be more optimized in coming days, Will work as Assetify module soon. But for this existing version replace `DxbaseTexture` & `dxUpdatebaseTexture` with `dxCreateScreenSource` and `dxUpdateScreenSource` respectively..
> 
> Yeah, i did it. What about `reverseCinemPointationPoint` function?

You can check this URL: Working version https://github.com/ov-sa/vRPZ-Framework/tree/main/%5BHandler%5D/cinecam_handler
Its inside utilities/
